# List of Brazilian cities based on your provided data, after removing non-Brazilian cities
cities_brazil = [
'Maceió', 
'Curitiba',
'São Caetano do Sul', 
'Porto Alegre',
'Porto União', 
'Tangará da Serra',
'Salvador', 
'Campo Grande',
'Bragança Paulista',
'Lins', 
'Belo Horizonte',
'Taubaté',
'Santiago',
'Jacareí',
'Goiânia',
'Rondonópolis',
'São Paulo',
'Centro Bandeirante',
'São Carlos',
'Rio de Janeiro', 
'São José',
'Nova Andradina',
'Natal',
'Teófilo Otoni',
'Nova Serrana',
'Barreiras',
'Penápolis',
'Alpinópolis',
'Cachoeira do Sul',
'Altamira',
'Juiz de Fora', 
'Ilhéus',
'Boca do Acre',
'Cuiabá',
'Fortaleza', 
'Vespasiano', 
'Teresina',
'Macapá',
'Três Lagoas',
'Feira de Santana', 
'Americana', 
'Primavera do Leste',
'Ribeirão Preto', 
'Quirinópolis',
'Aparecida de Goiânia', 
'Franca',
'Brusque',
'Pirassununga',
'Porto Velho',
'Cruzeiro',
'Presidente Venceslau',
'Ribeirão',
'São José dos Campos',
'Belém', 
'Palmas',
'João Pessoa', 
'Guarulhos',
'Marília',
'Itamarandiba',
'Brasília', 
'Lima Duarte', 
'Anápolis',
'Aracuai', 
'Araranguá', 
'Patrocínio',
'Além Paraíba',
'Ribeira de Oyster', 
'Santa Cruz do Sul',
'Itapema', 
'Maringá',
'Loanda',
'Campinas',
'Barba', 
'Cabo Frio', 
'Concórdia',
'Biguaçu',
'Vitória',
'Campos dos Goytacazes',
'Caxias do Sul', 
'Inhumas',
'Aracruz', 
'Capão da Canoa',
'Recife', 
'Lagoa Sul',
'Cascavel',
'Jaraguá do Sul',
'Araguaína', 
'Aquidauana', 
'São José do Rio Preto',
'Manaus',
'Rodeio Bonito',
'São Bernardo do Campo', 
'Joinville',
'Ibiá',
'Imperatriz',
'Serra',
'Cidade Velha',
'Taguatinga', 
'Tijucas', 
'Campo Mourão', 
'Canaã dos Carajás',
'Osasco',
'Sete Lagoas', 
'Parnaíba', 
'Mossoró', 
'Franca',
'Itajaí', 
'São Vicente',
'Resende',
'Macaé', 
'Itapipoca',
'São Luís',
'Colatina',
'Conselheiro Lafaiete', 
'Montanha Negra',
'Uruaçu',
'Paragominas',
'Piracicaba',
'Rio Verde',
'Valparaíso de Goiás',
'Curitibanos',
'Catalão',
'Fonte Bebida',
'Gurupi', 
'Patos de Minas',
'Jundiaí',
'Sorocaba',
'Barueri',
'Criciúma',
'Chapecó',
'Londrina',
'União da Vitória',
'Contagem',
'Alfenas',
'Araguari',
'Prata Nova',
'Cachoeira de Itapemirim',
'Passos',
'Arapiraca',
'Caetité',
'Paulínia',
'Petrolina',
'Cianorte',
'Juazeiro do Norte',
'Aracaju',
'Patos Brancos',
'Itumbiara',
'Niterói',
'Poá',
'Vitória da Conquista',
'Capela',
'Belo Vale',
'Nova Iguaçu',
'Boa Vista',
'Campina Grande',
'Ponta Grossa',
'Picos',
'Eunápolis',
'Caruaru',
'Uberlândia',
'Blumenau',
'Quixeramobim',
'Rio das Flores',
'Entre Rios de Minas',
'Alagoinhas',
'Jardim',
'Petrópolis', 
'Nova Friburgo',
'Santos', 
'Jataí',
'Xanxerê', 
'Lagoa Norte',
'Parauapebas',
'Marabá',
'Santo André',
'Santana de Parnaíba',
'Bom Jesus do Itabapoana',
'Santa Rosa',
'Rio Branco',
'Caieiras',
'Santa Helena de Goiás',
'Indaiatuba',
'Canoas',
'Santa Maria do Suaçuí',
'Caldas Novas',
'Gama', 
'Teresópolis',
'Praia Grande',
'Florianópolis', 
'Itatiba',
'Paranaíba',
'Montes Claros',
'Itatiaia',
'Presidente Prudente',
'Ourinhos', 
'Jaú', 
'Ipiaú',
'Foz do Iguaçu',
'Iturama',
'Jaboatão dos Guararapes',
'Presidente Kennedy',
'Governador Valadares',
'Mandaguari',
'Nova Lima',
'Ananindeua',
'São José de Ribamar', 
'São Lourenço',
'Ivaiporã',
'Planalto Sul',
'São Gotardo',
'Limeira', 
'Tubarão', 
'Tianguá',
'Angra dos Reis',
'Lagoa Seca', 
'Jaú',
'São Benedito do Sul',
'Itajubá', 
'Paulo Afonso',
'Guarantã do Norte',
'Ibitinga',
'Varginha',
'Aracati', 
'Barra do Herças', 
'Arcos',
'Guarapuava',
'Pontes e Lacerda',
'Ceres',
'Bom Jesus de Goiás',
'Mirassol',
'Tietê',
'São Sebastião',
'Santa Rita',
'Itapagipe', 
'Vinhedo', 
'Mineros',
'Jales',
'Guaxupé',
'Barra Mansa',
'Curvelo',
'Assis',
'José Bonifácio',
'Bragança',
'Vendas Novas do Imigrante', 
'Divinópolis',
'Machado', 
'Uberaba', 
'Campos Gerais',
'Maceio',
'Saint Caetano Of The South',
'Port Union', 
'Mountain Tangara',
'Braganca São Paulo',
'Lines',
'Taubate',
'Jacarei',
'Goiania',
'Rondonopolis',
'Rio De Janeiro',
'Saint Joseph',
'New Andradina',
'Teofilo Otoni', 
'New Serrana',
'Barriers', 
'Alpinopolis',
'South Waterfall',
'Judge Of Fora',
'Cuiaba',
'Vespasian',
'Three Lagoons',
'Feira De Santana',
'Eastern Spring',
'Ribeirao Preto',
'Quirinopolis', 
'Appearance Of Goiania',
'Old Port',
'President Venceslau',
'Bethlehem',
'John Person',
'Happy Landing',
'Guarapari',
'Marilia',
'Brasilia',
'Beyond Paraiba',
'Santa Cruz Do Sul',
'Maringa', 
'Cape Frio',
'Victory', 
'Goytacazes Fields', 
'Caxias Do Sul',
'Capão Da Canoa',
'Rattlesnake', 
'Jaragua', 
'Araguaina',
'Saint Joseph Of Rio Preto',
'Beautiful Rodeo', 
'Saint Bernard Of The Countryside',
'Old Town',
'Seven Lagoons', 
'Parnaiba', 
'Mossoro',
'Itajai',
'Macae',
'Saint Louis',
'Colatine',
'Advisor Lafaiete',
'Black Mountain',
'Green River',
'Valparaiso Of Goias',
'Catalan', 
'Jundiai',
'Criciuma',
'London',
'Union Of Victory',
'Count',
'New Silver',
'Itapemirim Waterfall',
'Bauru', 
'Mogi Of Crosses',
'Caetity',
'Paulinia', 
'Juazeiro Of The North', 
'White Duck',
'Poços De Caldas',
'Ituverava',
'Braganca',
'Itajuba',
'Guarantã Of The North',
'Muriaé',
'Aracatuba',
'Elói Mendes',
'Caraguatatuba',
'Divinopolis',
'Olinda', 
'Ariquemes',
'Cotia',
'Three Hearts',
'São Caetano Do Sul',
'Sobradinho',
'Tangará Da Serra', 
'Linhares',
'Núcleo Bandeirante',
'Santa Carmem',
'Cachoeira Do Sul',
'Juiz De Fora',
'Boca Da Mata',
'Primavera Do Leste', 
'Aparecida De Goiânia',
'Farroupilha',
'São José Dos Campos',
'Pouso Alegre', 
'Araçuaí',
'Rio Das Ostras',
'Barbalha',
'Campos Dos Goytacazes', 
'Lago Sul',
'Jaraguá',
'São José Do Rio Preto',
'São Bernardo Do Campo',
'Vila Velha',
'Canaã Dos Carajás', 
'Lages',
'Itaipulândia',
'Registro', 
'Serra Negra', 
'Valparaíso De Goiás',
'Bebedouro',
'Patos De Minas',
'Jacarezinho',
'União Da Vitória',
'Nova Prata',
'Cachoeiro De Itapemirim', 
'Passo Fundo', 
'Formiga',
'Goianésia',
'Balneário Camboriú', 
'Mogi Das Cruzes',
'Palhoça',
'Juazeiro Do Norte',
'Pato Branco',
'Vitória Da Conquista', 
'Capelinha', 
'Água Boa',
'Rio Das Flores',
'Entre Rios De Minas',
'Lago Norte',
'Santana De Parnaíba', 
'Nova Aurora',
'Bom Jesus Do Itabapoana',
'Santa Helena De Goiás',
'Santa Maria Do Suaçuí',
'Foz Do Iguaçu',
'Jaboatão Dos Guararapes',
'Maresias',
'São José De Ribamar',
'Duartina',
'Chapadão Do Sul',
'Pau Dos Ferros',
'Angra Dos Reis',
'São Bento Do Sul',
'Guarantã Do Norte',
'Querência',
'Dourados',
'Tupã', 
'Barra Do Garças',
'Pontes E Lacerda',
'Bom Jesus De Goiás',
'Itu',
'Crateús', 
'Frutuoso Gomes',
'Vitória Da Conquista',
'Presidente Bernardes',
'Ponta Porã',
'Venda Nova Do Imigrante',
'Munhoz', 
'Itapagé',
'Mineiros',
'Sao Paulo',
'Taboão Da Serra',
'Araçatuba', 
'Lagarto',
'Santa Rita Do Passa Quatro',
'São João De Meriti',
'Dom Cavati',
'Cabedelo',
'Três Corações',
'Porto Seguro',
'Recanto Das Emas'
]
